/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const avatarGroupInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['avatarGroupInjectionKey']
  const buttonGroupInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup.js')['buttonGroupInjectionKey']
  const defineShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['defineShortcuts']
  const extractShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['extractShortcuts']
  const formBusInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formBusInjectionKey']
  const formFieldInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formFieldInjectionKey']
  const formInputsInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formInputsInjectionKey']
  const formLoadingInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formLoadingInjectionKey']
  const formOptionsInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formOptionsInjectionKey']
  const inputIdInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['inputIdInjectionKey']
  const kbdKeysMap: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['kbdKeysMap']
  const modalInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useModal.js')['modalInjectionKey']
  const slideoverInjectionKey: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover.js')['slideoverInjectionKey']
  const useAvatarGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['useAvatarGroup']
  const useButtonGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup.js')['useButtonGroup']
  const useComponentIcons: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.js')['useComponentIcons']
  const useFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['useFormField']
  const useKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['useKbd']
  const useModal: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useModal.js')['useModal']
  const useSlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover.js')['useSlideover']
  const useToast: typeof import('./node_modules/.pnpm/@nuxt+ui@https+++pkg.pr.new+@nuxt+ui@d4a943e_@babel+parser@7.26.1_axios@1.7.7_drauu@0.4.1_emb_dg3t34z5vs7lh6s4qxdmaets3a/node_modules/@nuxt/ui/dist/runtime/composables/useToast.js')['useToast']
}
